### ISSUE TITLE
Allow q35 hotplugging in deployment tweaks

### ISSUE THREAD

**Issue by mzealey** [OpenNebula/addon-storpool#72]
Here's a deployment tweak script to fix https://github.com/OpenNebula/one/issues/4045

```
# Due to the nature of q35 model, there are no hotplugging slots available. See
# https://libvirt.org/pci-hotplug.html for more info. We need to hack the
# libvirt config (raw data) to have:
#
# pcie-root - normally autocreated but needs to be defined here
# pcie-to-pci-bridge - for legacy devices to hotplug to like virtio networking
# pcie-root-port - A large number of ports defined. The normal devices (disks
# etc) will take these first so we need a number of additional free ones.

machine_type = root.find("./os/type")
if 'q35' in machine_type.attrib['machine']:
    new_device = ET.SubElement(root, 'devices', {})

    ET.SubElement(new_device, 'controller', {
            'type': 'pci',
            'model': 'pcie-root'
        })
    for i in range(0,16):
        ET.SubElement(new_device, 'controller', {
                'type': 'pci',
                'model': 'pcie-root-port'
            })
    ET.SubElement(new_device, 'controller', {
            'type': 'pci',
            'model': 'pcie-to-pci-bridge'
        })

```

**Comment by atodorov-storpool** [comment]
Hi @mzealey 

I'll prepare a tweak script with add3ed option to customize the number of _pcie-root-port_ as VM attribute.
Also, I'd had issues with the contextualization cdrom -  q35 needed the cdrom to be attached as a SCSI device.
I'll try to create the tweak soon, depending on the other duties, though.

Best Regards,
Anton Todorov

**Comment by mzealey** [comment]
the cdrom issue on q35 is fixed in ON 5.10+ - it will put it onto sata controller rather than ide that it would use in 5.8.

**Comment by atodorov-storpool** [comment]
Hey @mzealey ,

Please test the proposed solution https://github.com/OpenNebula/addon-storpool/commit/d44ff85a98d13cd1e35e28a2e536d819eaf598ff

Best,
Anton

**Comment by mzealey** [comment]
looks good to me, I think we'll just go with the one I wrote though - I don't think there is a problem with shoving a load of pcie interfaces in to every vm?

**Comment by atodorov-storpool** [comment]
Thank you for the followup.

The option was introduced with dual-purpose - option to set the number of interfaces and option to disable this tweak.

I'm going to merge the change and close this issue.
