### ISSUE TITLE
Better hyperv settings for win 2016/2019

### ISSUE THREAD

**Issue by mzealey** [OpenNebula/addon-storpool#79]
For https://github.com/OpenNebula/addon-storpool/blob/master/vmm/kvm/deploy-tweaks.d.example/hyperv-clock.py change to:

```
clock = root.find("./clock")
hyperv = root.find("./features/hyperv")

if hyperv is not None:
    hyperv.append(ET.Element("synic", state = 'on'))
    hyperv.append(ET.Element("stimer", state = 'on'))
```

Previously idling was ~30-40% on those servers, now 1-3% cpu.

per https://serverfault.com/questions/955439/why-windows-10-virtual-machine-show-high-cpu-load-on-kvm-hyprvisor

**Comment by atodorov-storpool** [comment]
added via hv-enlightenments.py
to enable set in the USER_TEMPLATE
  T_HV_SYNIC = 1
  T_HV_STIMER = 1
