### ISSUE TITLE
Broken link in readme

### ISSUE THREAD

**Issue by spuder** [OpenNebula/addon-storpool#91]
This link is broken in the readme. I would fix the link, but I don't know where it is supposed to link to

![Screen Shot 2020-11-04 at 9 48 31 AM](https://user-images.githubusercontent.com/242382/98140701-f9c5be80-1e82-11eb-84d2-ca415d5d3dbf.png)

>For OpenNebula 5.10.x please use the following installation instructions For OpenNebula 5.6.x please use the following installation instructions For OpenNebula 5.4.x please use the following installation instructions

https://github.com/OpenNebula/addon-storpool/blob/master/docs/install-5.10.0.md

**Comment by atodorov-storpool** [comment]
Thank you for the reporting. The formatting is broken too. Will add the doc for the next release planned. There are some minor compatibility issues with ONE-EE that should be addressed first.

**Comment by atodorov-storpool** [comment]
I've unified the installation procedure to be compatible with OpenNebula 5.10+
