### ISSUE TITLE
Consider using virtinst Python module for editing libvirt xml?

### ISSUE THREAD

**Issue by ypid** [OpenNebula/addon-storpool#94]
Hi

I just found https://github.com/OpenNebula/addon-storpool/blob/master/vmm/kvm/deploy-tweaks.d.example/cpu.py

while playing with the `virt-xml` command on Debian from the [virtinst](https://packages.debian.org/buster/all/virtinst) package. This command uses this Python module:

```
/usr/share/virt-manager/virtinst/domain/cpu.py
```

Might that be helpful? I have not found any reference in this repo to virtinst or virt-xml.

PS: I currently don’t use OpenNebula, so if I am missing something please excuse.

**Comment by atodorov-storpool** [comment]
Hi @ypid 

These scripts are tightly tailored for use with OpenNebula and written as raw as possible to avoid dependency on additional modules/packages.

Best Regards,
Anton Todorov
